name: equalizer
channels:
- defaults
dependencies:
- mkl=2017.0.1=0
- numpy=1.12.0=py36_0
- pip=9.0.1=py36_1
- pyqt=5.6.0=py36_2
- python=3.6.0=0
- qt=5.6.2=0
- scipy=0.19.0=np112py36_0
- pip:
  - pyaudio==0.2.10
  - pyqtgraph=0.10.0

